BlogWebApp/BlogWebApp/Models/SubCategory.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.Build.Framework;
using System.ComponentModel;

namespace BlogWebApp.Models
{
    public class SubCategory : BaseEntity
    {

        [Required]
        [DisplayName("Sub Category Name")]
        public string SubCategoryName { get; set; }
        [Required]
        [DisplayName("Status")]
        public bool IsActive { get; set; }
        [Required]
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        [ValidateNever]
        public Category Category { get; set; }
    }
}

BlogWebApp/BlogWebApp/Areas/Admin/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogWebApp.Data;
using BlogWebApp.Models;
using BlogWebApp.Models.ViewModels;

namespace BlogWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        //Constructor to inject dependency.
        public SubCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET - Method to retrieve and display the list of subcategories.
        public async Task<IActionResult> Index()
        {
            //Retrieves all subcategories from datbase, including related entity category.
            var applicationDbContext = _context.SubCategory.Include(s => s.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET - Method to retrieve and display details of the selected Category.
        public async Task<IActionResult> Details(int? id)
        {
            //Checks if id or Db context is null. If so, return error message.
            if (id == null || _context.SubCategory == null)
            {
                return NotFound();
            }

            //Retrieves information of selected subcategory using id.
            var subCategory = await _context.SubCategory
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            //Checks if null. If so, returns error.
            if (subCategory == null)
            {
                return NotFound();
            }

            //Passes retrieved details and displays in Details view.
            return View(subCategory);
        }

        // GET - Method to display Create view for SubCategory.
        public IActionResult Create()
        {
            //Creates list of categories to be used for dropdown in view.
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName");
            //Returns Create view.
            return View();
        }

        // POST - Method to Create a new SubCategory.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubCategoryName,IsActive,CategoryId,Id,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SubCategory subCategory)
        {
            //Checks if Model state is valid.
            if (ModelState.IsValid)
            {
                //Add new subcategory to Db context.
                _context.Add(subCategory);
                //Save changes to database.
                await _context.SaveChangesAsync();
                //If successful, redirect to Index.
                return RedirectToAction(nameof(Index));
            }
            //If state not valid, repopulate ViewData with category list and return view with the subcategory data.
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET - Method to retrieve and diaplay details for Edit.
        public async Task<IActionResult> Edit(int? id)
        {
            //Check if sybcategory id or DbSet is null. If so, return erro.
            if (id == null || _context.SubCategory == null)
            {
                return NotFound();
            }

            //Retrieve subcategory from database by id.
            var subCategory = await _context.SubCategory.FindAsync(id);
            //Check if retrieved subcategory os null. If so, return error.
            if (subCategory == null)
            {
                return NotFound();
            }
            //Populate ViewData with category list dropdown and pass retrieved subcategory details to Edit view.
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName", subCategory.CategoryId);
            return View(subCategory);
        }

        // POST - Method to Edit a subcategory.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SubCategoryName,IsActive,CategoryId,Id,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SubCategory subCategory)
        {
            //Check if recieved id matches id or subcategory being edited. If not, return error.
            if (id != subCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Update subcategory details in Db context.
                    _context.Update(subCategory);
                    //Save changes to database.
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    //Check if subcategory with the id. If not, return error.
                    if (!SubCategoryExists(subCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        //Throw exception if concurrency issue.
                        throw;
                    }
                }
                //Redirect to Index view.
                return RedirectToAction(nameof(Index));
            }
            //Add list of categories to ViewData and return view with provided subcategory data.
            ViewData["CategoryId"] = new SelectList(_context.Category, "Id", "CategoryName", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET - Method to retrieve data to Delete a SubCategory.
        public async Task<IActionResult> Delete(int? id)
        {
            //Check if subcategory id or DbSet is null. If so, return error.
            if (id == null || _context.SubCategory == null)
            {
                return NotFound();
            }

            //Retrieve subcategory details from database by id, including category.
            var subCategory = await _context.SubCategory
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            //Check if subcategory is null. If so, return error.
            if (subCategory == null)
            {
                return NotFound();
            }

            //Pass retrieved subcategory details into Delete view.
            return View(subCategory);
        }

        // POST - Method to Delete a SubCategory.

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Check if SubCategory DbSet is null. If so, return problem response.
            if (_context.SubCategory == null)
            {
                return Problem("Entity set 'ApplicationDbContext.SubCategory'  is null.");
            }
            //Retrieve SubCategory from database by id.
            var subCategory = await _context.SubCategory.FindAsync(id);
            //heck if SubCategory exists.
            if (subCategory != null)
            {
                //Remove SubCategory from Db context
                _context.SubCategory.Remove(subCategory);
            }
            
            //Save changes to database and redirects to index.
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Helper method to check if SubCategory with specified id exists, and returns true/false.
        private bool SubCategoryExists(int id)
        {
          return (_context.SubCategory?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BlogWebApp/BlogWebApp/Areas/Admin/Views/SubCategories/Create.cshtml
@model BlogWebApp.Models.SubCategory

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Add a subcategory...</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SubCategoryName" class="control-label"></label>
                <input asp-for="SubCategoryName" class="form-control" />
                <span asp-validation-for="SubCategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary" onclick="return ValidationInput()">Submit</button>
                <a asp-area="Admin" asp-controller="SubCategories" asp-action="Index" class="btn btn-warning">
                    <i class="bi bi-arrow-left-square"></i>Back to List
                </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogWebApp/BlogWebApp/Areas/Admin/Views/SubCategories/Delete.cshtml
@model BlogWebApp.Models.SubCategory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this subcategory?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubCategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubCategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />

        <div class="col-md-12">
            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this subcategory?')" />
            <a asp-area="Admin" asp-controller="SubCategories" asp-action="Index" class="btn btn-warning">
                <i class="bi bi-arrow-left-square"></i>Back to List
            </a>
        </div>
    </form>
</div>

BlogWebApp/BlogWebApp/Areas/Admin/Views/SubCategories/Details.cshtml
@model BlogWebApp.Models.SubCategory

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SubCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubCategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubCategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BlogWebApp/BlogWebApp/Areas/Admin/Views/SubCategories/Edit.cshtml
@model BlogWebApp.Models.SubCategory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Modify subcategory...</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SubCategoryName" class="control-label"></label>
                <input asp-for="SubCategoryName" class="form-control" />
                <span asp-validation-for="SubCategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>

            <div class="col-md-12">
                <button type="submit" class="btn btn-primary" onclick="return ValidationInput()">Save</button>
                <a asp-area="Admin" asp-controller="SubCategories" asp-action="Index" class="btn btn-warning">
                    <i class="bi bi-arrow-left-square"></i>Back to List
                </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogWebApp/BlogWebApp/Areas/Admin/Views/SubCategories/Index.cshtml
@model IEnumerable<BlogWebApp.Models.SubCategory>

@{
    ViewData["Title"] = "Index";
}

<h1>Subcategory List</h1>


<div class="col-sm-6 d-flex-column flex-grow-0 align-items-center justify-content-end">
    <a asp-area="Admin" asp-controller="SubCategories" asp-action="Create"
       class="d-none d-sm-inline btn btm-sm btn-success shadow-sm">
        <i class="bi bi-plus-square" data-bs-toggle="tooltip" title="Add" style="font-size:15px"> Add New Category</i>
    </a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubCategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubCategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                    <div class="w-75 btn-group" role="group">

                        <a asp-area="Admin" asp-controller="SubCategories" asp-action="Edit" asp-route-id="@item.Id"
                           class="d-none d-sm-inline-flex btn btn-sm btn-primary shadow-sm">
                            <i class="bi bi-pencil-square" data-bs-toggle="tooltip" title="Edit" style="font-size:15px"> Edit</i>
                        </a>
                        <a asp-area="Admin" asp-controller="SubCategories" asp-action="Delete" asp-route-id="@item.Id"
                           class="d-none d-sm-inline-flex btn btn-sm btn-danger shadow-sm">
                            <i class="bi bi-x-square" data-bs-toggle="tooltip" title="Delete" style="font-size:15px"> Delete</i>
                        </a>
                    </div>

            </td>
        </tr>
}
    </tbody>
</table>