BlogWebApp/BlogWebApp/Models/BlogImages.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BlogWebApp.Models
{
    public class BlogImages : BaseEntity
    {
        [Required]
        [DisplayName("Blog Title")]
        public string BlogTitle { get; set; }

        [DisplayName("Image Url")]
        [ValidateNever]
        public string ImageUrl { get; set; }

        [Required]
        [DisplayName("Sub Category")]
        public int SubCategoryId { get; set; }

        [ValidateNever]
        public SubCategory subCategory { get; set; }
    }
}

BlogWebApp/BlogWebApp/Areas/Admin/Controllers/BlogImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogWebApp.Data;
using BlogWebApp.Models;
using BlogWebApp.Models.ViewModels;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static System.Net.Mime.MediaTypeNames;
using BlogWebApp.Data.Migrations;
using Microsoft.AspNetCore.Identity;

namespace BlogWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogImagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _applicationUser;
        private readonly IWebHostEnvironment _webHostEnvironment;

        //Constructor to inject dependencies.
        public BlogImagesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> applicationUser)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _applicationUser = applicationUser;

        }

        // GET - Method to retrieve and display the list of blogs images.
        public async Task<IActionResult> Index()
        {
            //Retrieves blogs from the database relating to this entity.
            var applicationDbContext = _context.BlogImages.Include(b => b.subCategory);
            //Returns list of blog images.
            return View(await applicationDbContext.ToListAsync());
        }

        // GET - Method to retrieve and display details of the selected blog image.
        public async Task<IActionResult> Details(int? id)
        {
            //Checks if id or Db context is null. If so returns error message.
            if (id == null || _context.BlogImages == null)
            {
                return NotFound();
            }

            //Retrieves information of the selected blog image using these entities.
            var blogImages = await _context.BlogImages
                .Include(b => b.subCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            //Checks if selected blog image is null. If so, returns error.
            if (blogImages == null)
            {
                return NotFound();
            }

            //Retrieves and displays details of selected blog images.
            return View(blogImages);
        }

        // GET - action method to Create a new blog image.
        public IActionResult Create()
        {
            //Initialises a new instance of BlogVM.
            BlogImagesVM obj = new()
            {
                //Initialises new blog image instance.
                BlogImages = new(),
                //Creates a subcategory list containing SubCategory Id and SubCategoryName.
                SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName")

            };
            //Passes the initialised BlogVM object to the Create view.
            return View(obj);
        }

        // POST - Action method to upload the added blog image.

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(BlogImagesVM obj, List<IFormFile>? files)
        {
            //Initialises list to store BlogImages object.
            List<BlogImages> objList = new List<BlogImages>();

            //Populates SubCategoryList properties of BlogVM.
            obj.SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName");

            {
                //Retrieves root path of wwwroot.
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                //Checks if file uploaded.
                if (files != null && files.Count > 0)
                {
                    //Iterates through uploaded files.
                    foreach (var file in files)
                    {
                        //Initialises new BlogImages instance.
                        BlogImages objSingle = new BlogImages();
                        //Generates unique file name and defines where it will be saved.
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(wwwRootPath, @"blogImages/images/");
                        //Gets file extension.
                        var extension = Path.GetExtension(file.FileName);
                        //Creates file stream and copies upoaded file to that directory.
                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        //Sets these properties foe the BlogImages object.
                        obj.BlogImages.ImageUrl = @"\blogImages\images\" + fileName + extension;
                        obj.BlogImages.CreatedBy = _applicationUser.GetUserId(HttpContext.User);
                        objSingle.BlogTitle = obj.BlogImages.BlogTitle;
                        objSingle.ImageUrl = obj.BlogImages.ImageUrl;
                        objSingle.SubCategoryId = obj.BlogImages.SubCategoryId;
                        objSingle.CreatedBy = obj.BlogImages.CreatedBy;
                        //Adds BlogImages to the list.
                        objList.Add(objSingle);
                    }

                    //Adds list of BlogImage objects to database and saves changes.
                    _context.BlogImages.AddRange(objList);
                    await _context.SaveChangesAsync();
                    //Success message displayed and redirected to Index.
                    TempData["success"] = "Blog Images uploaded successfully!";
                    return RedirectToAction("Index");
                }
            }
            //If no files uploaded, return view.
            return View(obj);
        }

        //Method to Edit blog images.
        public async Task<IActionResult> Edit(int? id)
        {
            //Checks if blog image id or DbSet is null. If so, returns error message.
            if (id == null || _context.BlogImages == null)
            {
                return NotFound();
            }

            //Retrieves selected blog image by its id.
            var blogImages = await _context.BlogImages.FindAsync(id);
            //Check if image is blog image is null. If so, redirect to Index.
            if (blogImages == null)
            {
                return RedirectToAction("Index");
            }

            //Initialises new instance of BlogImagesVM.
            BlogImagesVM objVM = new()
            {
                //Sets 'BlogImages' property with retrieved blog image object.
                BlogImages = blogImages,
                //For subcategory list containing SubCategory Id and SubCategoryName.
                SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName")
            };
            
            //Passes initialised BlogImagesVM object to the Edit view.
            return View(objVM);
         }


        // POST - Method to Edit blog images. 

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(BlogImagesVM obj, List<IFormFile>? files)
        {
            //Initialises list to store BlogImages objects.
            List<BlogImages> objList = new List<BlogImages>();
            //Populates SubCategoryList with this data. 
            obj.SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName");

            {
                //Retrieves root path.
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                //Check if files uploaded.
                if (files != null && files.Count > 0)
                {
                    //Iterates through each uploaded image.
                    foreach (var file in files)
                    {
                        //Initialises new object.
                        BlogImages objSingle = new BlogImages();
                        //Created unique file name and defines where it will be saved.
                        string fileName = Guid.NewGuid().ToString();
                        var uploads = Path.Combine(wwwRootPath, @"blogImages/images/");
                        //Gets file extension.
                        var extension = Path.GetExtension(file.FileName);

                        //Check if blog image already has an image.
                        if (obj.BlogImages.ImageUrl !=null)
                        {
                            //Constructs old image path and deletes pre-existing one.
                            var oldImagePath = Path.Combine(wwwRootPath, obj.BlogImages.ImageUrl.TrimStart('\\'));
                            if(System.IO.File.Exists(oldImagePath))
                            {
                                System.IO.File.Delete(oldImagePath);
                            }

                        }

                        //Creates file stream and copies uploaded file to defined directory.
                        using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }

                        //Updates changes ade to these properties.
                        obj.BlogImages.ImageUrl = @"\blogImages\images\" + fileName + extension;
                        obj.BlogImages.ModifiedBy = _applicationUser.GetUserId(HttpContext.User);
                        obj.BlogImages.ModifiedDate = DateTime.Now;

                    }

                    //Updates to database context and saves changes to database.
                    _context.BlogImages.Update(obj.BlogImages);
                    _context.SaveChanges();
                    

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Create.cshtml
@model BlogWebApp.Models.ViewModels.BlogImagesVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Add a new blog image...</h4>
<hr />
<div class="page-wrapepr">
    <div class="page title">
        <div class="row">

        </div>
    </div>
    <div class="page-body">
        <form method="post" enctype="multipart/form-data" class="row g-3 p-3">

            <div class="col-md-6">
                <label class="form-label" asp-for="BlogImages.SubCategoryId"></label>
                <select asp-for="BlogImages.SubCategoryId" id="ddlSubCategory" asp-items="@Model.SubCategoryList" class="form-control">
                    <option disabled selected>---Select Subcategory---</option>
                </select>
                <span asp-validation-for="BlogImages.SubCategoryId" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label class="form-label" asp-for="BlogImages.BlogTitle"></label>
               
                <input asp-for="BlogImages.BlogTitle" asp-items="@Model.SubCategoryList" class="form-control" />
                <span asp-validation-for="BlogImages.BlogTitle" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label class="form-label" asp-for="BlogImages.ImageUrl"></label>
                <input type="file" name="files" id="upload" multiple class="form-control" />
            </div>
            <div class="col-md-12">
                <button type="submit"  class="btn btn-primary" onclick="return ValidationInput()">Submit</button>
                <a asp-area="Admin" asp-controller="BlogImages" asp-action="Index" class="btn btn-warning">
                    <i class="bi bi-arrow-left-square"></i>Back to List
                </a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        function ValidInput() {
            if(document.getElementById("upload").value == ""){
               Sval.fire({
                   icon: "error",
                   title: "oops...",
                   text: "Image filed is required!",
                   footer: "<a href=Please upload image?</a>"
               });
               return false;
            }
            return true;
        }
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Delete.cshtml
@model BlogWebApp.Models.BlogImages

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this blog image?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subCategory.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />

        <div class="col-md-12">
            <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this blog image?')" />
            <a asp-area="Admin" asp-controller="BlogImages" asp-action="Index" class="btn btn-warning">
                <i class="bi bi-arrow-left-square"></i>Back to List
            </a>
        </div>
    </form>
</div>

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Details.cshtml
@model BlogWebApp.Models.BlogImages

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BlogImages</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BlogTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BlogTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.subCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.subCategory.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Edit.cshtml
@model BlogWebApp.Models.ViewModels.BlogImagesVM


<h1>Edit</h1>

<h4>Modify blog image...</h4>
<hr />

<div class="page-wrapper">
    <div class="page-title">
        <div class="row">
            <div class="col-sm-6 py-1">

            </div>
        </div>
    </div>

    <div class="page-body">
        <form method="post" enctype="multipart/form-data" class="row g-3 p-3">
            <input type="hidden" asp-for="BlogImages.Id" />
            <input type="hidden" asp-for="BlogImages.ImageUrl" />
            <input type="hidden" asp-for="BlogImages.CreatedBy" />
            <div class="col-md-6">
                <label class="form-label" asp-for="BlogImages.SubCategoryId"></label>
                <select asp-for="BlogImages.SubCategoryId" asp-items="@Model.SubCategoryList" class="form-control">
                    <option disabled selected>---Select Subcategory---</option>
                </select>
                <span asp-validation-for="BlogImages.SubCategoryId" class="text-danger"></span>
            </div>

            <div class="col-md-6">
                <label class="form-label" asp-for="BlogImages.BlogTitle"></label>
                <input asp-for="BlogImages.BlogTitle" class="form-control" />
                <span asp-validation-for="BlogImages.BlogTitle" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label class="form-label" asp-for="BlogImages.ImageUrl"></label>
                <input type="file" name="files" id="upload" multiple class="form-control" />
            </div>
            <div class="col-md-12">
                <button type="submit" class="btn btn-success"><i class="bi bi-plus-circle"></i>
                    Save</button>
                <a asp-area="Admin" asp-controller="BlogImages" asp-action="Index" class="btn btn-warning">
                    <i class="bi bi-arrow-left-square"></i> Back to List
                </a>
            </div>
        </form>

    </div>
</div>

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Edit1.cshtml
@model BlogWebApp.Models.BlogImages

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Modify blog image...</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label"></label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
  
                <input type="file" name="files" id="upload" asp-for="ImageUrl" multiple class="form-control" />

                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubCategoryId" class="control-label"></label>
                <select asp-for="SubCategoryId" class="form-control" asp-items="ViewBag.SubCategoryId"></select>
                <span asp-validation-for="SubCategoryId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> Submit
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">
        <i class="bi bi-arrow-left-square"></i>
        Back to List
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogWebApp/BlogWebApp/Areas/Admin/Views/BlogImages/Index.cshtml
@model IEnumerable<BlogImages>

<h1>Blog Images</h1>

<div class="table-wrapper">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-6 py-1">

            </div>
            <div class="col-sm-6 d-flex- flex-row align-items-center justify-content-end">
                <a asp-area="Admin" asp-controller="BlogImages" asp-action="Create"
                    class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"> <i class="bi bi-plus-square"></i>Upload Image(s)</a>            
             </div>
        </div>
    </div>


    <div class="accoridon" id="accordionExample">
        @foreach (var item in Model.Select (s=> s.BlogTitle).Distinct().ToList())
        {
            var itemData = Model.Where(s => s.BlogTitle == item).ToList();
            <div class="accordion-item">
                <h2 class="accordion-header" id="@itemData[0]".Id>
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapse_@itemData[0].Id" aria-expanded="false" aria-controls="collapse_@itemData[0].Id">
                    @itemData[0].BlogTitle
                </button>
                </h2>
          
    <div id="collapse_@itemData[0].Id" class="accordion-collapse collapse" aria-labelledby="@itemData[0].Id" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            @foreach (var itemData1 in Model.Where(s => s.BlogTitle == item).ToList())
                    {
                        <div class="bg-light d-flex justify-content-between">
                            <div><img src="@itemData1.ImageUrl" style="width:100px; height:100px"></div>
                            <div>
                                <div class="m-75 btn-group" role="group">
                                    <a asp-controller="BlogImages" asp-action="Edit" asp-route-id="@itemData1.Id" class="d-none d-sm-inline-flex btn btn-sm btn-primary shadow-sm">
                                    <i class="bi bi-pencil-square" data-bs-toggle="tooltip" title="Edit" style="font-size:15px"></i> Edit
                                    </a>
                                    <a asp-controller="BlogImages" asp-action="Delete" asp-route-id="@itemData1.Id" class="d-none d-sm-inline-flex btn btn-sm btn-danger shadow-sm">
                                                    <i class="bi bi-x-square" data-bs-toggle="tooltip" title="Delete" style="font-size:15px"></i> Delete
                                    </a>
                              </div>
                              </div>
                         </div>
                    }
                    </div>
                  </div>
                </div>
            }
        </div>
</div>