BlogWebApp/BlogWebApp/Models/Comments/MainComment.cs
namespace BlogWebApp.Models.Comments
{
    public class MainComment : Comment
    {
        public List<SubComment> SubComments { get; set; }
    }
}

BlogWebApp/BlogWebApp/Models/Comments/SubComment.cs
namespace BlogWebApp.Models.Comments
{
    public class SubComment : Comment
    {
        public int MainCommentId { get; set; }
    }
}

BlogWebApp/BlogWebApp/Areas/Admin/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogWebApp.Data;
using BlogWebApp.Models;
using Microsoft.AspNetCore.Identity;
using BlogWebApp.Models.ViewModels;
using BlogWebApp.Data.Migrations;

namespace BlogWebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _applicationUser;

        //Constructor to inject dependencies.
        public BlogController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> applicationUser)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _applicationUser = applicationUser;

        }

        //Method to retrieve and display the list of blogs.
        public async Task<IActionResult> Index()
        {
            //Retrieves blogs from the database relating to these entities.
            var applicationDbContext = _context.Blog.Include(b => b.ApplicationUser).Include(b => b.Category).Include(b => b.SubCategory);
            //Returns a list view of blogs.
            return View(await applicationDbContext.ToListAsync());
        }

        //Action method to retrieve and display details of the selected blog. 
        public async Task<IActionResult> Details(int? id)
        {
            //Checks if Blog id or DbSet is null.
            if (id == null || _context.Blog == null)
            {
                //Returns a 404 Not Found error message.
                return NotFound();
            }

            //Retrieves information of the selected blog, includes these entities.
            var blog = await _context.Blog
                .Include(b => b.ApplicationUser)
                .Include(b => b.Category)
                .Include(b => b.SubCategory)
                .FirstOrDefaultAsync(m => m.Id == id);

            //Checks if selected blog is null.
            if (blog == null)
            {
                //Returns a 404 Not Found error message.
                return NotFound();
            }

            //Passes selected blog's details to 'Details' view.
            return View(blog);
        }

        // GET - action method to create a new blog.
        public IActionResult Create()
        {
            //Initialises a new instance of BlogVM.
            BlogVM obj = new()
            {
                //Initialises new blog instance.
                blog = new(),
                //Creates a category list containing Category Id and CategoryName.
                CategoryList = new SelectList(_context.Category, "Id", "CategoryName"),
                //Creates a subcategory list containing SubCategory Id and SubCategoryName.
                SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName")

            };

            //Passes the initialised BlogVM object to the Create view.
            return View(obj);
        }

        // POST - Action method to publish the written blog.

        [HttpPost]
        [ValidateAntiForgeryToken] //To prevent cross-site request forgery attacks.

        public IActionResult Create(BlogVM obj, IFormFile? file)
        {
            {
                //Retrieves root path of wwwRootPath folder.
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                //Checks if file uploaded.
                if (file != null)
                {
                    //Generates unique file name using GUID where file is saved.
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"blogImages/titleImages/");
                    //Gets file extension.
                    var extension = Path.GetExtension(file.FileName);
                    //Creates file stream and copies file to directory.
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    //Sets titleImage URL for post.
                    obj.blog.TitleImageUrl = @"\blogImages\titleImages\" + fileName + extension;
                }

                //Sets these properties for the blog post.
                obj.blog.CreatedBy = _applicationUser.GetUserName(HttpContext.User);
                obj.blog.ApplicationUserId = _applicationUser.GetUserId(HttpContext.User);

                //Adds blog post to Db context and saves changes.
                _context.Blog.Add(obj.blog);
                _context.SaveChanges();

                //Success message displayed and redirected to Index.
                TempData["success"] = "Blog created successfully";
                return RedirectToAction("Index");

            }
           
            return View(obj);
        }
        
        //GET - Method to Edit a blog.
        public async Task<IActionResult> Edit(int? id)
        {
            //Checks if Blog id or DbSet is null.
            if (id == null || _context.Blog == null)
            {
                //Returns 404 Not Found error message.
                return NotFound();
            }

            //Retrieves blog with specified id from the database.
            var blogObj = await _context.Blog.FindAsync(id);
            //Checks if retrieved blog is null. If so, redirects to Index.
            if (blogObj == null)
            {
                return RedirectToAction("Index");
            }

            //Initialises new instance of BlogVM.
            BlogVM obj = new()
            {
                //Sets blog with retrieved blog object.
                blog = blogObj,
                //For Category and Subcategory lists.
                CategoryList = new SelectList(_context.Category, "Id", "CategoryName"),
                SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName")

            };

            return View(obj);
        }

        // POST - Method to Edit a blog.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BlogVM obj, IFormFile? file)
        {
            //Populates CategoryList and SubCategoryList properties of BlogVM.
            obj.CategoryList = new SelectList(_context.Category, "Id", "CategoryName");
            obj.SubCategoryList = new SelectList(_context.SubCategory, "Id", "SubCategoryName");

            {
                //Retrieves root path of wwwroot folder.
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                //Checks if file uploaded.
                if (file != null)
                {
                    //Initialises new blog object.
                    Blog objBlog = new Blog();
                    //Generates new unique file name and defines where it will be saved.
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"blogImages/titleImages/");
                    //Gets file extension.
                    var extension = Path.GetExtension(file.FileName);

                    //Checks if blog already has an image.
                    if (obj.blog.TitleImageUrl != null)
                    {
                        //Constructs old image pathway and deletes it if it exists.
                        var oldImagePath = Path.Combine(wwwRootPath, obj.blog.TitleImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }

                    }
                    //Creates file stream and copies uploaded image to directory.
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    //Updates these entities.
                    obj.blog.TitleImageUrl = @"\blogImages\titleImages\" + fileName + extension;
                    obj.blog.ModifiedBy = _applicationUser.GetUserId(HttpContext.User);
                    obj.blog.ModifiedDate = DateTime.Now;
                    obj.blog.ApplicationUserId = _applicationUser.GetUserId(HttpContext.User);
                }

                //Updates blog object in Db context and saves changes.
                _context.Update(obj.blog);
                await _context.SaveChangesAsync();

                //Success message displayed and redirection to Index.
                TempData["success"] = "Blog created successfully";
                return RedirectToAction("Index");

            }
            return View(obj);
        }

        // GET - Retrieves and displays details of selected blog to delete.
        public async Task<IActionResult> Delete(int? id)
        {
            //Checks if Blog id or Db set is null.
            if (id == null || _context.Blog == null)
            {
                //Returns 404 Not Found error message.
                return NotFound();
            }

            //Retrieves these details of the selected blog.
            var blog = await _context.Blog
                .Include(b => b.ApplicationUser)
                .Include(b => b.Category)
                .Include(b => b.SubCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            //Checks if selected blog is null.
            if (blog == null)
            {
                //Returns 404 Not Found error message.
                return NotFound();
            }

            //Passes retrieved details to the Delete view.

BlogWebApp/BlogWebApp/ViewComponents/TopHeaderMenuViewComponent.cs
using BlogWebApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogWebApp.ViewComponents
{
    public class TopHeaderMenuViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        //Constructor to inject dependency.
        public TopHeaderMenuViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        //Method to call view component.
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //Retrieves all categories from database.
            var categories = _context.Category.ToList();
            //Loops through each category to retrieve itssubcategories.
            foreach (var item in categories)
            {
                //Retrieves and assigns subcategories for category.
                item.SubCategories = _context.SubCategory.Where(s => s.CategoryId == item.Id).ToList();            }

            //Returns view dropdown with category data.
            return await Task.FromResult((IViewComponentResult)View("TopMenu", categories));


        }
    }
}

BlogWebApp/BlogWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <h3 class="navbar-brand">BeMe</h3>
                <a class="navbar-brand">
                    <img src="~/my_logo.webp" alt="logo" height="50" width="50"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    @(await Component.InvokeAsync("TopHeaderMenu"))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <div class="row g-5">
                <div class="col-md-8">
                    @RenderBody()
                </div>
                <div class="col-md-4">
                    <div class="position-sticky" style="top: 2rem;">
                        <div class="p-4 mb-3 bg-body-tertiary rounded">
                            <h4 class="fst-italic">About</h4>
                            <p class="mb-0">BeMe is a hobby-based social blogging platform that aims to motivate and inspire those looking to start a hobby, while providing support to individuals who want to share and discuss their interests.
                                This application hopes to offers a platform to connect with like-minded individuals who share similar interests.</p>
                        </div>

                    </div>
                </div>
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWebApp/BlogWebApp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title Admin</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"></link>
    <link href="~/css/site-admin.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="~/summernote/summernote-lite.css" rel="stylesheet" />
    <script src="~/summernote/summernote-lite.js"></script>
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <h3 class="navbar-brand">BeMe</h3>
                <a class="navbar-brand">
                    <img src="~/my_logo.webp" alt="logo" height="50" width="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Settings
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="AdminDashboard" asp-action="Users">Manage Users</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Category</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="SubCategories" asp-action="Index">Subcategory</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="BlogImages" asp-action="Index">Upload Image</a></li>                                
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_NotificationAlert" />
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWebApp/BlogWebApp/Views/Shared/_LayoutAuthor.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title Author</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"></link>
    <link href="~/css/site-admin.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="~/summernote/summernote-lite.css" rel="stylesheet" />
    <script src="~/summernote/summernote-lite.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <h3 class="navbar-brand">BeMe</h3>
                <a class="navbar-brand">
                    <img src="~/my_logo.webp" alt="logo" height="50" width="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Author" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <partial name="_NotificationAlert" />
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWebApp/BlogWebApp/Views/Shared/_LayoutSubscriber.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="Subscriber" asp-controller="SubscriberDashboard" asp-action="Index">BlogWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    @(await Component.InvokeAsync("TopHeaderMenu"))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <div class="row g-5">
                <div class="col-md-8">
                    @RenderBody()
                </div>
                <div class="col-md-4">
                    <div class="position-sticky" style="top: 2rem;">
                        <div class="p-4 mb-3 bg-body-tertiary rounded">
                            <h4 class="fst-italic">About</h4>
                            <p class="mb-0">
                                BeMe is a hobby-based social blogging platform that aims to motivate and inspire those looking to start a hobby, while providing support to individuals who want to share and discuss their interests.
                                This application hopes to offers a platform to connect with like-minded individuals who share similar interests.
                            </p>
                        </div>

                    </div>
                </div>
            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWebApp/BlogWebApp/Views/Shared/_MainComment.cshtml
@model BlogWebApp.Models.ViewModels.CommentVM

@{ 

}

<div>
    <form method="post" asp-controller="Home" asp-action="Comment">
        <input asp-for="PostId" type="hidden" />
        <input asp-for="MainCommentId" type="hidden" />
        <input asp-for="Message" />
        <span asp-validation-for="Message"></span>
        <button type="submit">Submit</button>
    </form>
</div>

BlogWebApp/BlogWebApp/Views/Shared/_NotificationAlert.cshtml
@if(TempData["success"] !=null)
{
    <script src="~/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right"",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut: "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.success('@TempData["success"]')

    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right"",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut: "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.error('@TempData["error"]')

    </script>

}

BlogWebApp/BlogWebApp/Views/Shared/_SubComment.cshtml
@model BlogWebApp.Models.ViewModels.CommentVM
@{
}

<div>
    <form method="post" asp-controller="Home" asp-action="Comment">
        <input asp-for="PostId" type="hidden" />
        <input asp-for="MainCommentId" type="hidden" />
        <input style="width: 100px" asp-for="Message" />
        <span asp-validation-for="Message"></span>
        <button type="submit">Submit</button>
    </form>
</div>